[features]
seeds = false
skip-lint = false
[programs.localnet]
donate = "7hTffwGm6YkPK5rC4N1LfSQvZkr97ZvGQX4qVY7w77ht"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
